### PR TITLE
Altered Delayed::Command to work with or without Rails

### PR DESCRIPTION
**Pull request by bethesque**
When running the delayed_job daemon in a codebase without Rails, we've had to create a fake Rails module to provide the logger and root methods that Delayed::Command expects. Given the rest of the delayed job code can run without Rails, it would be nice if the Command behaved the same way.

Please let me know if the tests are sufficient or not. Given the entire class was lacking a test, I have only added tests for the code that I altered.

### CODE REVIEW

**Comment by betesh** [comment]
This PR assumes that if Rails is defined, the entire Rails stack is loaded.  This is not necessarily the case.  See rails/rails-html-sanitizer#25 / rails/rails-html-sanitizer#26

A more robust approach would use `defined?(Rails.root)` and `defined?(Rails.logger)` individually.

**Comment by betesh** [comment]
:+1:

**Comment by paulspringett** [comment]
@bethesque any progress with this? I'm keen on seeing this merged so happy to take a look at sorting the specs.

**Comment by bethesque** [comment]
I have modified the code as per @betesh's suggestion, to check for the existence of Rails.logger and Rails.root separately. It should be good to pull now, let me know if there are any changes you would like.

**Comment by bethesque** [comment]
Damn you Rubocop! Double quotes are fine! http://viget.com/extend/just-use-double-quoted-ruby-strings

The merge build is failing because the double logger is leaking across example intermittently. I've noticed other intermittent failures as I've been running the tests. Is this normal?

**Comment by bethesque** [comment]
Fixed.

**Comment by paulspringett** [comment]
@bethesque thank you! @albus522 @sferik could this be merged please?

**Comment by sferik** [comment]
Looks great. Thanks!

**Pull request merged**
