### PR TITLE
Recursively create daemons pid directory

### PR DESCRIPTION
**Pull request by bizrad6**
Allow users to specify a not yet created nested pid directory.

### CODE REVIEW

**Comment by albus522** [comment]
Curious where you are creating a pid directory that you need the nesting.

Also, please remove the .gitignore change

**Comment by bizrad6** [comment]
The default location of the pid directory is in `{root}/tmp/pids` so, by default, it is a nested directory.  If a project does not have a `{root}/tmp` directory then the current code raises an exception.  Also, if a user provides a path that does not already exist via a command line argument then it also raises an exception. Not requiring the user to define the path beforehand seems like a nice feature.

Will remove the `.gitignore` changes...

**Comment by bizrad6** [comment]
Should I close this or is there interest in merging in these changes?

**Comment by bizrad6** [comment]
Thanks!

**Pull request merged**
