### PR TITLE
fix: ActiveSupport 7.0.3 Compatibility

### PR DESCRIPTION
**Pull request by arielvalentin**
Fixes https://github.com/collectiveidea/delayed_job/issues/1168

### CODE REVIEW

**Comment by arielvalentin** [comment]
👋🏼 @willnet @albus522 I see you are the most recent contributors to the project and was hoping to get some feedback from you all re: this PR. 

https://github.com/collectiveidea/delayed_job/graphs/contributors?from=2021-05-29&to=2022-06-04&type=c

**Comment by arielvalentin** [comment]
Ping @willnet @albus522 🙏🏼

**Comment by arielvalentin** [comment]
Ping @willnet @albus522

**Comment by willnet** [comment]
As I commented https://github.com/collectiveidea/delayed_job/issues/1168#issuecomment-1167099869 LGTM, but I'm not a committer so I can't merge this PR.

**Comment by arielvalentin** [comment]
my apologies @willnet 

Is @albus522 still a maintainer?

**Pull request merged**
