### PR TITLE
rails 6.1 compatibility

### PR DESCRIPTION
**Pull request by gigorok**
in order to upgrade to rails 6.1 we have to fix activesupport dependency

### CODE REVIEW

**Comment by nehresma** [comment]
According to the Rails blog, 6.1 is due out this week (the week of Dec 7th):  https://weblog.rubyonrails.org/2020/12/1/Rails-6-1-rc2-release/

**Comment by albus522** [comment]
I am working on getting a Rails 6.1 release together. First, I ended up needing to switch over to Github Actions because Travis is now unbearably slow for open source builds. The move to Github Actions made this pretty much unmergable, so I have a replacement PR up here #1129 checking the build. I hope to have everything ready to go soon.

**Comment by nehresma** [comment]
Thank you @albus522 for your work with this gem.

**Comment by albus522** [comment]
Ok. `delayed_job` is released, over to https://github.com/collectiveidea/delayed_job_active_record

**Pull request closed without merging**
