### PR TITLE
updated queues attribute name in readme

### PR DESCRIPTION
**Pull request by jvenezia**

### CODE REVIEW

**Comment by rbmrclo** [comment]
+1 on this. This gave me an enlightenment after few minutes of debugging the error below.

```
Delayed::Worker.queue_attributes
NoMethodError: undefined method `queue_attributes' for Delayed::Worker:Class
```

**Comment by rbmrclo** [comment]
`Delayed::Worker.queue_attributes` is correct. You should be able to use it once you've used the `4.1.2` version.

https://github.com/collectiveidea/delayed_job/blob/master/CHANGELOG.md#412---2016-05-16

**Comment by jvenezia** [comment]
Thanks @rbmrclo I guess it was not clear enough at the time I made this PR.

Closing.

**Comment by rbmrclo** [comment]
Yup. I know that this has been left opened for a long time already and there's probably a misleading part in the README during the time that it has been encountered.

It's just that I ran with the same issue today but this PR also helped me realized the problem. Thanks @jvenezia! Happy to help too!

**Pull request closed without merging**
