### PR TITLE
Loosen version constraints to support Rails 5.1

### PR DESCRIPTION
**Pull request by dsander**

### CODE REVIEW

**Comment by zavan** [comment]
@albus522 Can this be released, please?

**Comment by matthewrudy** [comment]
Needs the same on delayed_job_activerecord too

**Comment by axlekb** [comment]
@albus522 I saw you closed a deprecation issue for this repository two days ago. Could you give this a quick look, merge and release?

**Comment by albus522** [comment]
@axlekb things are mostly ready here, but it appears DJ AR is not in as good of shape. So yes and no. Also I would like to add that commenting on and closing an issue is no where near the effort required to push out a proper release. Unfortunately I have been pretty busy and haven't had the time yet to properly push out a new release. Hopefully I can do so soon, but unfortunately I can not commit to a date right now because it all depends on when I can manage to carve out some time.

**Comment by axlekb** [comment]
Thanks for the update!  Much appreciated!

**Comment by pboling** [comment]
Released version 4.1.3 does raise the version constraint on Rails... so is this done now?

**Comment by albus522** [comment]
Yes. In master now

**Pull request closed without merging**
