### PR TITLE
Update tasks.rb

### PR DESCRIPTION
**Pull request by baweaver**
@radar had mentioned not being able to start multiple workers at once. Can something like this be added to alleviate that issue?

### CODE REVIEW

**Comment by radar** [comment]
Yes please, this would be very nice :)

**Comment by albus522** [comment]
That doesn't actually work. That tries to run multiple workers in one process, not multiple processes. You could use fork within the process, but then you have to in house a process manager which we don't want to do.

To run multiple workers, you simply run the same rake command multiple times.

**Comment by albus522** [comment]
You can also use ```bin/delayed_job```. See https://github.com/collectiveidea/delayed_job#running-jobs

**Comment by radar** [comment]
How do I generate bin/delayed_job?

**Comment by albus522** [comment]
```rails generate delayed_job:active_record```

**Pull request closed without merging**
